apiVersion: v1
kind: ServiceAccount
metadata:
  name: tidb-operator
  namespace: {{namespace}}
  labels:
    app: tidb-operator
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: tidb-operator
  labels:
    app: tidb-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: tidb-operator
  namespace: {{namespace}}
---
kind: Service
apiVersion: v1
metadata:
  name: tidb-operator
  namespace: {{namespace}}
  labels:
    app: tidb-operator
spec:
  type: NodePort
  ports:
  - port: 12808
    targetPort: 12808
    nodePort: 12808
  selector:
    app: tidb-operator
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: tidb-operator
  labels:
    app: tidb-operator
  namespace: {{namespace}}
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tidb-operator
  template:
    metadata:
      labels:
        app: tidb-operator
    spec:
      serviceAccountName: tidb-operator
      containers:
      - name: tidb-operator
        resources:
          limits:
            cpu: 250m
            memory: "256Mi"
        ports:
        - containerPort: 10228
          protocol: TCP
        command:
          - bash
          - "-c"
          - |
            tidb-operator \
              -runmode={{runMode}} \
              -http-addr=${POD_IP} \
              -init-md={{initMd}}
        image: {{registry}}/tidb-operator:{{version}}
        imagePullPolicy: Always
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: TZ
          value: "Asia/Shanghai"
      # Comment the following tolerations if Dashboard must not be deployed on master
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule