apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: pull-image
spec:
  template:
    metadata:
      labels:
        name: pull-image
    spec:
      containers:
        - name: pd
          image: 10.209.224.13:10500/ffan/rds/pd:{{version}}
          imagePullPolicy: Always
          command:
            - bash
            - "-c"
            - echo "waiting close"
        - name: tikv
          image: 10.209.224.13:10500/ffan/rds/tikv:{{version}}
          imagePullPolicy: Always
          command: 
            - bash
            - "-c"
            - echo "waiting close"
        - name: tidb
          image: 10.209.224.13:10500/ffan/rds/tidb:{{version}}
          imagePullPolicy: Always
          command: 
            - bash
            - "-c"
            - echo "waiting close"
      restartPolicy: Always