apiVersion: v1
kind: Service
metadata:
  name: prom-gateway
  labels:
    name: prom-gateway
spec:
  selector:
    name: prom-gateway
  type: ClusterIP
  ports:
    - port: 9091
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: prom-gateway
  labels:
    name: prom-gateway
spec:
  replicas: 1
  selector:
    name: prom-gateway
  template:
    metadata:
      labels:
        name: prom-gateway
    spec:
      nodeSelector:
        node-role: prometheus
      containers:
      - name: prom-gateway
        image: 10.209.224.13:10500/rds/pushgateway:latest
        env: 
        - name: TZ
          value: "Asia/Shanghai"
        ports:
          - containerPort: 9091
      # tolerations:
      # - key: node-role.prometheus
      #   effect: NoSchedule
