apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    name: grafana
spec:
  selector:
    name: grafana
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 12802
  type: NodePort
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: grafana
  labels:
    name: grafana
spec:
  replicas: 1
  selector:
    name: grafana
  template:
    metadata:
      labels:
        name: grafana
    spec:
      nodeSelector:
        node-role: prometheus
      containers:
      - name: grafana
        image:  grafana/grafana
        env:
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        ports:
          - containerPort: 3000
        volumeMounts:
          - name: grafana-data
            mountPath: /var/lib/grafana
      volumes:
        - name: grafana-data
          hostPath: {path: /var/lib/grafana}
      tolerations:
      - key: node-role.prometheus
      # - key: node-role.kubernetes.io/master
        effect: NoSchedule
