apiVersion: v1
kind: Pod
metadata:
  name: migration-{{cell}}
  labels:
    app: tidb
    cell: {{cell}}
    component: migration
spec:
  volumes:
    - name: syslog
      hostPath: {path: /dev/log}
    - name: zone
      hostPath: {path: /etc/localtime}
  terminationGracePeriodSeconds: 10
  containers:
  - name: migration
    image: {{image}}
    resources:
      limits:
        cpu: "200m"
        memory: "512Mi"
    command:
      - bash
      - "-c"
      - |
        migrate {{sync}}
        while true; do
          echo "Waiting for the pod to closed"
          sleep 10
        done
    volumeMounts:
      - name: zone
        mountPath: /etc/localtime
    env: 
    - name: M_S_HOST
      value: "{{sh}}"
    - name: M_S_PORT
      value: "{{sP}}"
    - name: M_S_USER
      value: "{{su}}"
    - name: M_S_PASSWORD
      value: "{{sp}}"
    - name: M_S_DB
      value: "{{db}}"
    - name: M_D_HOST
      value: "{{dh}}"
    - name: M_D_PORT
      value: "{{dP}}"
    - name: M_D_USER
      value: "{{duser}}"
    - name: M_D_PASSWORD
      value: "{{dp}}"
    - name: M_STAT_API
      value: "{{api}}"