---
# Regular service for load balancing client connections.
kind: Service
apiVersion: v1
metadata:
  name: pd-{{cell}}
  labels:
    component: pd
    cell: {{cell}}
    app: tidb
spec:
  ports:
    - name: client
      port: 2379
  selector:
    component: pd
    cell: {{cell}}
    app: tidb
  type: NodePort
---
# https://kubernetes.io/docs/admin/dns/
# https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/
# Headless service for etcd cluster bootstrap.
kind: Service
apiVersion: v1
metadata:
  name: srv-{{cell}}
  labels:
    component: pd
    cell: {{cell}}
    app: tidb
spec:
  clusterIP: None
  ports:
    - name: pd-server
      port: 2380
  selector:
    component: pd
    cell: {{cell}}
    app: tidb