---
# Regular service for load balancing client connections.
kind: Service
apiVersion: v1
metadata:
  name: pd-{{cell}}
  labels:
    component: pd
    cell: {{cell}}
    app: tidb
spec:
  ports:
    - port: 2379
  selector:
    component: pd
    cell: {{cell}}
    app: tidb
  type: NodePort
---
# https://kubernetes.io/docs/admin/dns/ 用于容器启动时判断是否所有replica的pod都准备好
# Headless service for etcd cluster bootstrap.
kind: Service
apiVersion: v1
metadata:
  name: pd-{{cell}}-srv
  labels:
    component: pd
    cell: {{cell}}
    app: tidb
spec:
  clusterIP: None
  ports:
    - name: pd-server
      port: 2380
  selector:
    component: pd
    cell: {{cell}}
    app: tidb
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: pd-{{cell}}
spec:
  replicas: {{replicas}}
  template:
    metadata:
      labels:
        component: pd
        cell: {{cell}}
        app: tidb
    spec:
      volumes:
        - name: datadir
          emptyDir: {}
        - name: syslog
          hostPath: {path: /dev/log}
        - name: zone
          hostPath: {path: /etc/localtime}
      # 默认是30s
      terminationGracePeriodSeconds: 30
      containers:
        - name: pd
          image: {{registry}}/pd:{{version}}
          # imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: datadir
              mountPath: /data
            - name: syslog
              mountPath: /dev/log
            - name: zone
              mountPath: /etc/localtime
          resources:
            limits:
              memory: "{{mem}}Mi"
              cpu: "{{cpu}}m"
          command:
            - bash
            - "-c"
            - |
              ipaddr=$(hostname -i)
              client_urls="http://0.0.0.0:2379"
              advertise_client_urls="http://$ipaddr:2379"
              peer_urls="http://0.0.0.0:2380"
              advertise_peer_urls="http://$ipaddr:2380"

              export CLIENT_URLS=$client_urls
              export ADVERTISE_CLIENT_URLS=$advertise_client_urls
              export PEER_URLS=$peer_urls
              export ADVERTISE_PEER_URLS=$advertise_peer_urls
              export PD_DATA_DIR=/data/$HOSTNAME

              # 获取该pod在dns中的id
              until [ $(getid {{cell}} | wc -l) -eq 1 ]; do
                echo "Cannt get current pod id in SRV record, $(getid {{cell}} | tr '\n' '')"
                sleep 1
              done
              export PD_NAME=$(getid {{cell}})
              # 保存pdname到本地文件，prestop hook会用来删除member
              echo $PD_NAME > pod
              echo -e "\033[31mCurrent pod id is $PD_NAME\033[0m"

              # Pd 会根据$PD_DATA_DIR目录是否存在来判断是否为一个新的member,还是resuming
              # 在此不做任何处理. main.go:56
              if [ -d $PD_DATA_DIR ]; then
                echo "Resuming with existing data dir:$PD_DATA_DIR"
              else
                echo "First run for this member"
              fi

              # If there's already a functioning cluster, join it.
              # 获取集群的leader，如果有的化则join it.重试3次(在扩容时会导致不能访问)，每次不超过3s
              resp=''
              for i in $(seq 1 3)  
              do  
                resp=$(curl --connect-timeout 1 --write-out %{http_code} --silent --output /dev/null http://pd-{{cell}}:2379/pd/api/v1/leader)
                if [ $resp == 200 ]
                then
                  break
                fi
                sleep 1   
              done  
              if [ $resp == 200 ]
              then
                echo "Joining existing cluster:http://pd-{{cell}}:2379"
                pd-server \
                --name="$PD_NAME" \
                --data-dir="$PD_DATA_DIR" \
                --client-urls="$CLIENT_URLS" \
                --advertise-client-urls="$ADVERTISE_CLIENT_URLS" \
                --peer-urls="$PEER_URLS" \
                --advertise-peer-urls="$ADVERTISE_PEER_URLS" \
                --join="http://pd-{{cell}}:2379" \
                --config="/etc/pd/config.toml"
              else
                # Join failed. Assume we're trying to bootstrap.
                echo "Create a new pd cluster"
                # First wait for the desired number of replicas to show up.
                echo "Waiting for {{replicas}} replicas in SRV record for pd-{{cell}}-srv..."
                until [ $(getpods {{cell}} | wc -l) -eq {{replicas}} ]; do
                  echo "[$(date)] waiting for {{replicas}} entries in SRV record for pd-{{cell}}-srv"
                  sleep 1
                done

                urls=$(getpods {{cell}} | tr '\n' ',')
                urls=${urls%,}
                echo "Initial-cluster:$urls"

                # Now run
                pd-server \
                --name="$PD_NAME" \
                --data-dir="$PD_DATA_DIR" \
                --client-urls="$CLIENT_URLS" \
                --advertise-client-urls="$ADVERTISE_CLIENT_URLS" \
                --peer-urls="$PEER_URLS" \
                --advertise-peer-urls="$ADVERTISE_PEER_URLS" \
                --initial-cluster-state=new \
                --initial-cluster=$urls \
                --config="/etc/pd/config.toml"
              fi
          lifecycle:
            preStop:
              exec:
                command:
                  - bash
                  - "-c"
                  - |
                    PD_NAME=$(cat pod)
                    # clear
                    resp=''
                    for i in $(seq 1 3)  
                    do  
                      resp=$(curl -X DELETE --write-out %{http_code} --silent --output /dev/null http://pd-{{cell}}:2379/pd/api/v1/members/$PD_NAME)
                      if [ $resp == 200 ]
                      then
                        break
                      fi 
                      sleep 1  
                    done
                    if [ $resp == 200 ]
                    then
                      echo 'Delete pd "$PD_NAME" success'
                    fi