---
kind: Service
apiVersion: v1
metadata:
  name: tidb-{{cell}}
  labels:
    component: tidb
    cell: {{cell}}
    app: tidb
spec:
  ports:
    - name: mysql
      port: 4000
    - name: web
      port: 10080
  selector:
    component: tidb
    cell: {{cell}}
    app: tidb
  # sessionAffinity: ClientIP
  type: NodePort
---
kind: ReplicationController
apiVersion: v1
metadata:
  name: tidb-{{cell}}
spec:
  replicas: {{replicas}}
  template:
    metadata:
      labels:
        component: tidb
        cell: {{cell}}
        app: tidb
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: tidb
        image: {{registry}}/tidb:{{version}}
        livenessProbe:
          httpGet:
            path: /status
            port: 10080
          initialDelaySeconds: 30
          timeoutSeconds: 5
        resources:
          limits:
            memory: "{{mem}}Mi"
            cpu: "{{cpu}}m"
        command: ["/tidb-server"]
        args: 
          - -P=4000
          - --store=tikv
          - --path=pd-{{cell}}:2379
          - --metrics-addr=prom-gateway:9091
          - --metrics-interval=15
        env: 
          - name: TZ
            value: "Asia/Shanghai"