---
kind: Service
apiVersion: v1
metadata:
  name: tidb-{{cell}}
  labels:
    component: tidb
    cell: {{cell}}
    app: tidb
spec:
  ports:
    - name: mysql
      port: 4000
    - name: web
      port: 10080
  selector:
    component: tidb
    cell: {{cell}}
    app: tidb
  sessionAffinity: ClientIP
  type: NodePort
---
kind: ReplicationController
apiVersion: v1
metadata:
  name: tidb-{{cell}}
spec:
  replicas: {{replicas}}
  template:
    metadata:
      labels:
        component: tidb
        cell: {{cell}}
        app: tidb
    spec:
      affinity:
        # TiDB 和 TiKV 实例，建议分开部署，以免竞争 CPU 资源，影响性能
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 80
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: component
                  operator: In
                  values:
                  - "tikv"
              topologyKey: kubernetes.io/hostname
      volumes:
        - name: syslog
          hostPath: {path: /dev/log}
        - name: zone
          hostPath: {path: /etc/localtime}
      terminationGracePeriodSeconds: 5
      containers:
        - name: tidb
          image: {{registry}}/tidb:{{version}}
          livenessProbe:
            httpGet:
              path: /status
              port: 10080
            initialDelaySeconds: 30
            timeoutSeconds: 5
          volumeMounts:
            - name: syslog
              mountPath: /dev/log
            - name: zone
              mountPath: /etc/localtime
          resources:
            limits:
              memory: "{{mem}}Mi"
              cpu: "{{cpu}}m"
          command: ["/tidb-server"]
          args: 
            - -P=4000
            - --store=tikv
            - --path=pd-{{cell}}:2379
            - --metrics-addr=prom-gateway:9091
            - --metrics-interval=15