apiVersion: v1
kind: Pod
metadata:
  name: tikv-{{cell}}-{{id}}
  labels:
    app: tidb
    cell: {{cell}}
    component: tikv
    id: "{{id}}"
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role
            operator: NotIn
            values:
            - prometheus
    # PD 和 TiKV 实例，建议每个实例单独部署一个硬盘，避免 IO 冲突，影响性能
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 80
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: component
              operator: In
              values:
              - "pd"
          topologyKey: kubernetes.io/hostname
  volumes:
    - name: syslog
      hostPath: {path: /dev/log}
    - name: datadir
      {{tidbdata_volume}}
    - name: zone
      hostPath: {path: /etc/localtime}
  terminationGracePeriodSeconds: 30
  containers:
  - name: tikv
    image: {{registry}}/tikv:{{version}}
    resources:
      # 初始化requests和limits相同的值，是为了防止memory超过requests时，node资源不足，导致该pod被重新安排到其它node
      requests:
        memory: "{{mem}}Mi"
        cpu: "{{cpu}}m"
      limits:
        memory: "{{mem}}Mi"
        cpu: "{{cpu}}m"
    ports:
    - containerPort: 20160
    volumeMounts:
      - name: datadir
        mountPath: /data
      - name: zone
        mountPath: /etc/localtime
    command:
      - bash
      - "-c"
      - |
        /tikv-server \
        --store="/data/tikv-{{cell}}-{{id}}" \
        --addr="0.0.0.0:20160" \
        --capacity={{capacity}}GB \
        --advertise-addr="$POD_IP:20160" \
        --pd="pd-{{cell}}:2379" \
        --config="/etc/tikv/config.toml"
    env: 
      - name: POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
    lifecycle:
      preStop:
        exec:
          command:
            - bash
            - "-c"
            - |
              rm -rf /data/tikv-{{cell}}-{{id}}