swagger: "2.0"
info: {}
basePath: /tidb/api/v1
paths:
  /metadata/:
    get:
      tags:
      - metadata
      description: get all metatada
      operationId: MetadataController.GetAll
      responses:
        "200":
          schema:
            $ref: '#/definitions/operator.Metadata'
        "404":
          description: not find
        "500":
          description: etcd error
    put:
      tags:
      - metadata
      description: update the metadata
      operationId: MetadataController.Update
      parameters:
      - in: body
        name: body
        description: body for metadata content
        required: true
        schema:
          $ref: '#/definitions/operator.Metadata'
      responses:
        "200": {}
        "400":
          description: bad request
        "500":
          description: cannt store metadata
  /metadata/{key}:
    get:
      tags:
      - metadata
      description: get sub metadata by key
      operationId: MetadataController.Get
      parameters:
      - in: path
        name: key
        description: The key for metadata property
        required: true
        type: string
      responses:
        "200":
          description: '{string}'
        "404":
          description: :key not found
  /tidbs/:
    post:
      tags:
      - tidbs
      description: create a tidb
      operationId: TidbController.CreateTidb
      parameters:
      - in: body
        name: body
        description: body for tidb content
        required: true
        schema:
          $ref: '#/definitions/operator.Db'
      responses:
        "200": {}
        "403":
          description: body is empty
  /tidbs/{cell}:
    get:
      tags:
      - tidbs
      description: get tidb by cell
      operationId: TidbController.Get
      parameters:
      - in: path
        name: cell
        description: The cell for tidb name
        required: true
        type: string
      responses:
        "200":
          schema:
            $ref: '#/definitions/operator.Db'
        "404":
          description: :key not found
    delete:
      tags:
      - tidbs
      description: delete the tidb from user
      operationId: TidbController.Delete tidb
      parameters:
      - in: path
        name: cell
        description: The cell you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: cell is empty
  /tidbs/{cell}/events:
    get:
      tags:
      - tidbs
      description: get all events
      operationId: TidbController.GetEvents
      parameters:
      - in: path
        name: cell
        description: The cell for tidb name
        required: true
        type: string
      responses:
        "200":
          schema:
            $ref: '#/definitions/operator.Events'
  /tidbs/{cell}/migrate:
    post:
      tags:
      - tidbs
      description: migrate mysql data to tidb
      operationId: TidbController.Migrate
      parameters:
      - in: query
        name: sync
        description: increment sync
        type: string
      - in: path
        name: cell
        description: The database name for tidb
        required: true
        type: string
      - in: body
        name: body
        description: Body for src mysql
        required: true
        schema:
          $ref: '#/definitions/.Mysql'
      responses:
        "200": {}
        "403":
          description: body is empty
  /tidbs/{cell}/scale:
    patch:
      tags:
      - tidbs
      description: scale tidb
      operationId: TidbController.ScaleTidb
      parameters:
      - in: path
        name: cell
        description: The cell for pd name
        required: true
        type: string
      - in: body
        name: body
        description: 'The body data type is {dbReplica: int, kvReplica: int} for scale
          content'
        required: true
      responses:
        "200": {}
        "403":
          description: body is empty
  /tidbs/{cell}/status:
    patch:
      tags:
      - tidbs
      description: patch tidb status
      operationId: TidbController.status
      parameters:
      - in: path
        name: cell
        description: The cell for pd name
        required: true
        type: string
      - in: body
        name: body
        description: 'The body data type is {''type'': string, status'': string}'
        required: true
      responses:
        "200": {}
        "400":
          description: body is empty
        "403":
          description: unsupport operation
  /tidbs/{user}/limit:
    post:
      tags:
      - tidbs
      description: whether the user creates tidb for approval
      operationId: TidbController.CheckResources
      parameters:
      - in: path
        name: user
        description: The user id
        required: true
        type: string
      - in: body
        name: body
        description: body for resource content
        required: true
        schema:
          $ref: '#/definitions/operator.ApprovalConditions'
      responses:
        "200": {}
        "403":
          description: body is empty
  /users/{user}/tidbs:
    get:
      tags:
      - users
      description: Get tidbs by user
      operationId: UserController.GetTidbsByUser
      parameters:
      - in: path
        name: user
        description: The user id
        required: true
        type: string
      responses:
        "200":
          schema:
            type: array
            items:
              $ref: '#/definitions/controllers.Dbs'
        "404":
          description: :user not found
definitions:
  .Mutex:
    type: object
  .Mysql:
    type: object
  .ObjectMeta:
    type: object
  .TypeMeta:
    type: object
  controllers.Dbs:
    title: Dbs
    type: object
    properties:
      tidbs:
        type: array
        items:
          $ref: '#/definitions/operator.Db'
      total:
        type: integer
        format: int64
  operator.ApprovalConditions:
    title: ApprovalConditions
    type: object
    properties:
      dbr:
        type: integer
        format: int32
      kvr:
        type: integer
        format: int32
  operator.Db:
    title: Db
    type: object
    properties:
      metadata:
        $ref: '#/definitions/metav1.ObjectMeta'
      owner:
        $ref: '#/definitions/operator.Owner'
      pd:
        $ref: '#/definitions/operator.Pd'
      schema:
        $ref: '#/definitions/operator.Schema'
      status:
        $ref: '#/definitions/operator.Status'
      tidb:
        $ref: '#/definitions/operator.Tidb'
      tikv:
        $ref: '#/definitions/operator.Tikv'
  operator.Event:
    title: Event
    type: object
    properties:
      cell:
        type: string
      first:
        type: string
        format: string
      key:
        type: string
      last:
        type: string
        format: string
      msg:
        type: string
      sc:
        type: string
      type:
        type: string
  operator.Events:
    title: Events
    type: object
    properties:
      events:
        type: array
        items:
          $ref: '#/definitions/operator.Event'
      metadata:
        $ref: '#/definitions/metav1.ObjectMeta'
  operator.K8s:
    title: K8s
    type: object
    properties:
      proxys:
        type: string
      volume:
        type: string
  operator.Member:
    title: Member
    type: object
    properties:
      id:
        type: integer
        format: int64
      state:
        type: integer
        format: int64
  operator.MetaSpec:
    title: MetaSpec
    type: object
    properties:
      ac:
        $ref: '#/definitions/operator.ApprovalConditions'
      k8s:
        $ref: '#/definitions/operator.K8s'
      pd:
        $ref: '#/definitions/operator.Unit'
      specifications:
        type: array
        items:
          $ref: '#/definitions/operator.Specification'
      tidb:
        $ref: '#/definitions/operator.Unit'
      tikv:
        $ref: '#/definitions/operator.Unit'
      versions: {}
  operator.Metadata:
    title: Metadata
    type: object
    properties:
      metadata:
        $ref: '#/definitions/metav1.ObjectMeta'
      spec:
        $ref: '#/definitions/operator.MetaSpec'
  operator.Owner:
    title: Owner
    type: object
    properties:
      desc:
        type: string
      reason:
        type: string
      userId:
        type: string
      userName:
        type: string
  operator.Pd:
    title: Spec
    type: object
    properties:
      capatity:
        type: integer
        format: int64
      cpu:
        type: integer
        format: int64
      innerAddresses: {}
      mem:
        type: integer
        format: int64
      member:
        type: integer
        format: int64
      members:
        $ref: '#/definitions/operator.Member'
      outerAddresses: {}
      replicas:
        type: integer
        format: int64
      tidbdata_volume:
        type: string
      version:
        type: string
  operator.Phase:
    type: object
  operator.Preference:
    title: Preference
    type: object
    properties:
      desc:
        type: string
      name:
        type: string
      replicas:
        $ref: '#/definitions/operator.Replicas'
  operator.Replicas:
    type: object
  operator.Schema:
    title: Schema
    type: object
    properties:
      name:
        type: string
      password:
        type: string
      user:
        type: string
  operator.Spec:
    title: Spec
    type: object
    properties:
      capatity:
        type: integer
        format: int64
      cpu:
        type: integer
        format: int64
      mem:
        type: integer
        format: int64
      replicas:
        type: integer
        format: int64
      tidbdata_volume:
        type: string
      version:
        type: string
  operator.Specification:
    title: Specification
    type: object
    properties:
      desc:
        type: string
      name:
        type: string
      preferences:
        type: array
        items:
          $ref: '#/definitions/operator.Preference'
  operator.Status:
    title: Status
    type: object
    properties:
      available:
        type: boolean
      desc:
        type: string
      migrateState:
        type: string
      outerAddresses: {}
      outerStatusAddresses: {}
      phase:
        $ref: '#/definitions/operator.Phase'
      scaleState:
        type: integer
        format: int64
  operator.Store:
    title: Store
    type: object
    properties:
      address:
        type: string
      id:
        type: integer
        format: int64
      nodeName:
        type: string
      state:
        type: integer
        format: int64
  operator.Tidb:
    title: Spec
    type: object
    properties:
      capatity:
        type: integer
        format: int64
      cpu:
        type: integer
        format: int64
      mem:
        type: integer
        format: int64
      replicas:
        type: integer
        format: int64
      tidbdata_volume:
        type: string
      version:
        type: string
  operator.Tikv:
    title: Spec
    type: object
    properties:
      availableReplicas:
        type: integer
        format: int64
      capatity:
        type: integer
        format: int64
      cpu:
        type: integer
        format: int64
      cur:
        type: string
      mem:
        type: integer
        format: int64
      member:
        type: integer
        format: int64
      readyReplicas:
        type: integer
        format: int64
      replicas:
        type: integer
        format: int64
      stores:
        $ref: '#/definitions/54755.Store'
      tidbdata_volume:
        type: string
      version:
        type: string
  operator.Unit:
    title: Unit
    type: object
    properties:
      capacity:
        type: integer
        format: int64
      cpu:
        type: integer
        format: int64
      max:
        type: integer
        format: int64
      memory:
        type: integer
        format: int64
tags:
- name: metadata
  description: |
    MetadataController operations about metadata
- name: tidbs
  description: |
    TidbController operations about tidb
- name: users
  description: |
    UserController operations about all tidbs
